apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentspring.fullname" . }}-console
spec:
  replicas: 1
  selector:
    matchLabels: { app: {{ include "agentspring.name" . }}, component: console }
  template:
    metadata:
      labels: { app: {{ include "agentspring.name" . }}, component: console }
    spec:
      containers:
        - name: console
          image: "{{ .Values.consoleImage.repository }}:{{ .Values.consoleImage.tag }}"
          imagePullPolicy: {{ .Values.consoleImage.pullPolicy }}
          ports: [{ containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentspring.fullname" . }}-console
spec:
  type: {{ .Values.consoleService.type }}
  selector: { app: {{ include "agentspring.name" . }}, component: console }
  ports:
    - port: {{ .Values.consoleService.port }}
      targetPort: 80
      name: http
